name: myAutomatisation

on: 
  push:
    branches: [ "main"]
    
    
jobs: 
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello step
      run : echo "Hello from github actions!"
      
    - name: clone repository
      uses: actions/checkout@v3
      
    - name: List directories
      run : ls -la
  
  bye:
    runs-on: ubuntu-latest
    
    steps:
      - name: Bye step
        run : echo "Bye bye"!
  
  run-script:
    runs-on : ubuntu-latest
    
    steps:
      - name: clone repository
        uses: actions/checkout@v3
    
      - name: Instal Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Run my script
        run : python3 myNumbers.py
    
