name: myAutomatisation

on: 
  push:
    branches: [ "main"]
    
    
jobs: 
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello step
      run : echo "Hello from github actions!"
      
    - name: List directories
      run : ls -la
      
    - name: clone repository
      uses: actions/checkout@v3
  
  bye:
    runs-on: ubuntu-latest
    needs: [hello]
    
    steps:
      - name: Bye step
        run : echo "Bye bye"!
    
    
    
    
   
  
    

  
